### ISSUE TITLE
Clicking Crafting Button with Item on Cursor

### ISSUE THREAD

**Issue by RoboMWM** [BenWoodworth/FastCraftPlus#20]
I initially thought this was an NCP issue - but other reports seem to suggest otherwise.

Other reports: https://www.spigotmc.org/threads/fastcraft.133803/page-5#post-1453130 and https://aquifermc.org/threads/server-crash-what-happen.114/ (possibly)

https://gist.github.com/RoboMWM/bcc4b73ccbee3a7199ae40772c283dee

```
2016-04-02 23:44:47 [INFO] piggywiggy1999 has just earned the achievement [Benchmarking]
2016-04-02 23:44:49 [INFO] [NoCheatPlus] piggywiggy1999 failed FastClick: tried to move items in their inventory too quickly. VL 91.
2016-04-02 23:44:50 [INFO] [NoCheatPlus] missxgamer failed FastClick: tried to move items in their inventory too quickly. VL 91.
2016-04-02 23:44:50 [INFO] [NoCheatPlus] Music_girl_13 failed FastClick: tried to move items in their inventory too quickly. VL 91.
2016-04-02 23:44:55 [INFO] [NoCheatPlus] thenameislexie failed FastClick: tried to move items in their inventory too quickly. VL 91.
2016-04-02 23:44:56 [FATAL] Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:810) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.2.jar:git-Paper-628]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_72]
Caused by: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_72]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.Container.getSlot(Container.java:109) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1921) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.2.jar:git-Paper-628]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[patched_1.9.2.jar:git-Paper-628]
	... 5 more
2016-04-02 23:44:59 [INFO] [NoCheatPlus] Music_girl_13 failed FastClick: tried to move items in their inventory too quickly. VL 149383.
2016-04-02 23:45:00 [INFO] [NoCheatPlus] missxgamer failed FastClick: tried to move items in their inventory too quickly. VL 74692.
2016-04-02 23:45:05 [FATAL] Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:810) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.2.jar:git-Paper-628]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_72]
Caused by: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_72]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.Container.getSlot(Container.java:109) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1921) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.2.jar:git-Paper-628]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[patched_1.9.2.jar:git-Paper-628]
	... 5 more
```

```
2016-04-02 23:55:38 [INFO] [NoCheatPlus] thenameislexie failed FastClick: tried to move items in their inventory too quickly. VL 149392.
2016-04-02 23:55:48 [INFO] [NoCheatPlus] Music_girl_13 failed FastClick: tried to move items in their inventory too quickly. VL 373465.
2016-04-02 23:56:15 [INFO] piggywiggy1999 issued server command: /help
2016-04-02 23:56:22 [INFO] thenameislexie issued server command: /unclaim
2016-04-02 23:56:35 [INFO] [NoCheatPlus] Music_girl_13 failed FastClick: tried to move items in their inventory too quickly. VL 448147.
2016-04-02 23:56:37 [FATAL] Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:810) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.2.jar:git-Paper-628]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_72]
Caused by: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_72]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.Container.getSlot(Container.java:109) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1921) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.2.jar:git-Paper-628]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[patched_1.9.2.jar:git-Paper-628]
	... 5 more
```

**Comment by BenWoodworth** [comment]
Can you see if this is still an issue in v0.9?

**Comment by RoboMWM** [comment]
Unsure if this is actually FastCraft or NCP's error, as the guy in the AquiferMC post is not running FastCraft+. Could be a generic inventory error? (This report can also be found here: https://github.com/NoCheatPlus/Issues/issues/149 )

**Comment by Jikoo** [comment]
This is caused by clicking on the icon to open the 3x3 crafting grid with an item on your cursor. I was just about to open a new issue, but I was sure I'd seen this before.

# Debug Output
```
[00:30:30] [Server thread/INFO]: [FastCraftPlus] FastCraft+ Debug Info:

========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.17
  git-Spigot-5a40365-b70058a (MC: 1.9.2)
  1.9.2-R0.1-SNAPSHOT
  Java 1.8.0_45
Other Plugins (0):
===========================================
```

# Stack Trace
```
[00:27:57] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_45]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_45]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-b70058a]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_45]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_45]
        at net.minecraft.server.v1_9_R1.Container.getSlot(Container.java:109) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1890) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        ... 5 more
```

**Comment by BenWoodworth** [comment]
Interesting. I'll be looking into it.

**Comment by BenWoodworth** [comment]
I found the problem. When you click on the workbench button, an InventoryClickEvent is run, a new inventory is shown, and since the event is cancelled, bukkit tries to revert the picked up item by putting it back in the inventory slot it was picked up from. Since the inventory currently showing is smaller than the inventory that was open for the event, it's trying to put the item back in a slot that no longer exists. To fix this, I just wait a tick to open the workbench inventory.
