### ISSUE TITLE
Java Error - Shaped Recipes

### ISSUE THREAD

**Issue by Drag0nz69** [BenWoodworth/FastCraftPlus#31]
Remove these top lines, and replace all {brace-enclosed text}.

# Description
With v0.13 I am now getting a java error whenever I click on a workbench. This only occurs with "Shaped" recipes. If I comment them out of the config, the error is not present. My configuration was working fine with v0.12.

Config: http://pastebin.com/TcnhL81Q

# Debug Output
<details>
    <summary>Show **/fcadmin debug** output</summary>
    <code>{========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.13
  git-Spigot-5a40365-f631379 (MC: 1.9.2)
  1.9.2-R0.1-SNAPSHOT
  Java 1.8.0_71
Other Plugins (16):
  AsyncWorldEditInjector 3.3.0
  AsyncWorldEdit 3.3.2
  PlaceholderAPI 2.3.8
  PermissionsEx 1.23.4
  ChatControl 6.8.7
  CommandSync 2.3
  Vault 1.5.6-b49
  ProtocolLib 3.7.0-BETA
  WorldEdit 6.1.1-SNAPSHOT;3459-94ae1be
  Essentials 2.0.1-b339
  EssentialsProtect 2.0.1-b339
  EssentialsGeoIP 2.0.1-b339
  EssentialsAntiBuild 2.0.1-b339
  EssentialsSpawn 2.0.1-b339
  WorldGuard 6.1
  VentureChat 2.8.4
===========================================}</code>
</details>

# Stack Trace
<details>
    <summary>Show stack trace</summary>
    <code>{[08:04:29] [Server thread/WARN]: java.lang.NullPointerException
[08:04:29] [Server thread/WARN]: 	at co.kepler.fastcraftplus.recipes.RecipeUtil.hashRecipe(RecipeUtil.java:313)
[08:04:29] [Server thread/WARN]: 	at co.kepler.fastcraftplus.compat.Compat_FastCraftPlus.getRecipes(Compat_FastCraftPlus.java:41)
[08:04:29] [Server thread/WARN]: 	at co.kepler.fastcraftplus.compat.RecipeCompatManager.getRecipes(RecipeCompatManager.java:74)
[08:04:29] [Server thread/WARN]: 	at co.kepler.fastcraftplus.craftgui.LayoutRecipesItems.<init>(LayoutRecipesItems.java:19)
[08:04:29] [Server thread/WARN]: 	at co.kepler.fastcraftplus.craftgui.LayoutFastCraft.<init>(LayoutFastCraft.java:25)
[08:04:29] [Server thread/WARN]: 	at co.kepler.fastcraftplus.craftgui.GUIFastCraft.<init>(GUIFastCraft.java:59)
[08:04:29] [Server thread/WARN]: 	at co.kepler.fastcraftplus.craftgui.PlayerManager$2.run(PlayerManager.java:85)
[08:04:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[08:04:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[08:04:29] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[08:04:29] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[08:04:29] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[08:04:29] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[08:04:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)}</code>
</details>

**Comment by BenWoodworth** [comment]
This seems to be working in v0.15. Can you let me know if it's fixed?

**Comment by Drag0nz69** [comment]
This appears to be fixed in 0.15 - I am no longer getting the errors.

**Comment by BenWoodworth** [comment]
Okay, thanks!
