### ISSUE TITLE
Can't craft things on Thermos

### ISSUE THREAD

**Issue by Xuwznln** [BenWoodworth/FastCraftPlus#37]
I use fastcraft+ on Thermos. When I open a workbench, and the server shows error logs.I also can't craft things

Debug Info:
<details><summary>Show **/fcadmin debug** output</summary>
```
========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.16
  1.7.10-1614.46 (MC: 1.7.10)
  1.7.10-R0.1-SNAPSHOT
  Java 1.8.0_77
Other Plugins (43):
  AsyncWorldEditInjector 2.2.2
  CoreProtect 2.0.8
  WorldEdit 6.1;no_git_id
  PixelmonGym 5.0
  OpenInv 2.3.6
  Essentials Pre2.13.1.2
  RemoteToolkitPlugin R10_A15.3
  GroupManager 2.0 (2.12.1) (Phoenix)
  PlayerSQL 2.1
  PlugMan 1.8.4
  BukkitWebby 1.1.0
  ProtocolLib 3.6.5
  AsyncKeepAlive 1.1
  LogAll 2.0.1
  NetherPortalRescue 1.1.1
  CloudTrade 1.5
  AsyncWorldEdit 2.2.2
  NoSpawnChunks 0.3
  CommandChat 1.0
  EssentialsProtect Pre2.13.1.2
  IceWalker 1.0
  Multikills 1.5.7-Build#136
  EssentialsChat Pre2.13.1.2
  BanItem 2.7
  EssentialsAntiBuild Pre2.13.1.2
  CommandCode 1.0
  RandomBox 2.4.4
  BossShop 2.0.5
  Vault 1.2.31-b411
  EssentialsSpawn Pre2.13.1.2
  ScriptBlock 0.8.7
  NeverLag 1.3.0
  HolographicDisplays 2.1.10
  PlotSquared 3.3.0
  SyncUserPerm 1.0
  VipZero 1.2.2
  PlayerPoints 2.1.4
  ChestCommands 3.1.3
  Residence 2.6.6.6
  Treasure_Hunt 1.0
  GlobalMarket 1.3.0-11
  Gifts 1.0
  LockettePro 1.9.2
===========================================
```
</details>

<details><summary>Show stack trace</summary>
```
 [10:27:51] [Server thread/INFO]: [FastCraftPlus] Created directory: plugins\FastCraftPlus\preferences
 [10:27:51] [Server thread/INFO]: [FastCraftPlus] Created preferences file for iamasadone
 [10:27:51] [Server thread/WARN]: java.lang.NullPointerException
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.recipes.RecipeUtil.getItemName(RecipeUtil.java:130)
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.recipes.Ingredient.<init>(Ingredient.java:30)
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit$FastRecipeCompat.<init>(Compat_Bukkit.java:130)
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit.loadRecipe(Compat_Bukkit.java:91)
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit.getRecipe(Compat_Bukkit.java:62)
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit.getRecipes(Compat_Bukkit.java:46)
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.RecipeCompatManager.getRecipes(RecipeCompatManager.java:74)
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.LayoutRecipesItems.<init>(LayoutRecipesItems.java:19)
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.LayoutFastCraft.<init>(LayoutFastCraft.java:25)
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.GUIFastCraft.<init>(GUIFastCraft.java:59)
 [10:27:51] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.PlayerManager.onPlayerInteract(PlayerManager.java:46)
 [10:27:51] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [10:27:51] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 [10:27:51] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 [10:27:51] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
 [10:27:51] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
 [10:27:51] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
 [10:27:51] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
 [10:27:51] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
 [10:27:51] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223)
 [10:27:51] [Server thread/WARN]: at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:429)
 [10:27:51] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853)
 [10:27:51] [Server thread/WARN]: at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
 [10:27:51] [Server thread/WARN]: at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
 [10:27:51] [Server thread/WARN]: at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
 [10:27:51] [Server thread/WARN]: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
 [10:27:51] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013)
 [10:27:51] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
 [10:27:51] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
 [10:27:51] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
 [10:27:51] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
 [10:28:19] [Server thread/WARN]: java.lang.NullPointerException
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.recipes.RecipeUtil.getItemName(RecipeUtil.java:130)
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.recipes.Ingredient.<init>(Ingredient.java:30)
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit$FastRecipeCompat.<init>(Compat_Bukkit.java:130)
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit.loadRecipe(Compat_Bukkit.java:91)
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit.getRecipe(Compat_Bukkit.java:62)
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit.getRecipes(Compat_Bukkit.java:46)
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.RecipeCompatManager.getRecipes(RecipeCompatManager.java:74)
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.LayoutRecipesItems.<init>(LayoutRecipesItems.java:19)
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.LayoutFastCraft.<init>(LayoutFastCraft.java:25)
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.GUIFastCraft.<init>(GUIFastCraft.java:59)
 [10:28:19] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.PlayerManager.onPlayerInteract(PlayerManager.java:46)
 [10:28:19] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [10:28:19] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 [10:28:19] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 [10:28:19] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
 [10:28:19] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
 [10:28:19] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
 [10:28:19] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
 [10:28:19] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
 [10:28:19] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223)
 [10:28:19] [Server thread/WARN]: at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:429)
 [10:28:19] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853)
 [10:28:19] [Server thread/WARN]: at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
 [10:28:19] [Server thread/WARN]: at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
 [10:28:19] [Server thread/WARN]: at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
 [10:28:19] [Server thread/WARN]: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
 [10:28:19] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013)
 [10:28:19] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
 [10:28:19] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
 [10:28:19] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
 [10:28:19] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
 [10:28:33] [Server thread/WARN]: java.lang.NullPointerException
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.recipes.RecipeUtil.getItemName(RecipeUtil.java:130)
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.recipes.Ingredient.<init>(Ingredient.java:30)
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit$FastRecipeCompat.<init>(Compat_Bukkit.java:130)
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit.loadRecipe(Compat_Bukkit.java:91)
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit.getRecipe(Compat_Bukkit.java:62)
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.Compat_Bukkit.getRecipes(Compat_Bukkit.java:46)
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.compat.RecipeCompatManager.getRecipes(RecipeCompatManager.java:74)
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.LayoutRecipesItems.<init>(LayoutRecipesItems.java:19)
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.LayoutFastCraft.<init>(LayoutFastCraft.java:25)
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.GUIFastCraft.<init>(GUIFastCraft.java:59)
 [10:28:33] [Server thread/WARN]: at co.kepler.fastcraftplus.craftgui.PlayerManager.onPlayerInteract(PlayerManager.java:46)
 [10:28:33] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [10:28:33] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 [10:28:33] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 [10:28:33] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
 [10:28:33] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
 [10:28:33] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
 [10:28:33] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
 [10:28:33] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
 [10:28:33] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223)
 [10:28:33] [Server thread/WARN]: at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:429)
 [10:28:33] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853)
 [10:28:33] [Server thread/WARN]: at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
 [10:28:33] [Server thread/WARN]: at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
 [10:28:33] [Server thread/WARN]: at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
 [10:28:33] [Server thread/WARN]: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
 [10:28:33] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013)
 [10:28:33] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
 [10:28:33] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
 [10:28:33] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
 [10:28:33] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
```
</details>

**Comment by BenWoodworth** [comment]
[Line throwing error](https://github.com/BenWoodworth/FastCraftPlus/blob/v0.16/src/main/java/co/kepler/fastcraftplus/recipes/RecipeUtil.java#L130)

**Comment by BenWoodworth** [comment]
Is there an error when you startup the plugin?

**Comment by Xuwznln** [comment]
It didn't show error logs when I started my server with FastCraftPlus1.6. But with the latest version FastCraftPlus , it showed another error.
[12:50:38] [Server thread/INFO]: [FastCraftPlus] Enabling FastCraftPlus v0.18
[12:50:38] [Server thread/WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/CraftingManager
[12:50:38] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[12:50:38] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[12:50:38] [Server thread/WARN]: 	at co.kepler.fastcraftplus.recipes.RecipeUtil.<clinit>(RecipeUtil.java:41)
[12:50:38] [Server thread/WARN]: 	at co.kepler.fastcraftplus.FastCraft.onEnable(FastCraft.java:37)
[12:50:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[12:50:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[12:50:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[12:50:38] [Server thread/WARN]: 	at com.ryanclancy000.plugman.utilities.Utilities.loadPlugin(Utilities.java:294)
[12:50:38] [Server thread/WARN]: 	at com.ryanclancy000.plugman.utilities.Utilities.reloadCommand(Utilities.java:423)
[12:50:38] [Server thread/WARN]: 	at com.ryanclancy000.plugman.PlugManCommands.onCommand(PlugManCommands.java:82)
[12:50:38] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:50:38] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[12:50:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[12:50:38] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1366)
[12:50:38] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1103)
[12:50:38] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[12:50:38] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[12:50:38] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[12:50:38] [Server thread/WARN]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[12:50:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013)
[12:50:38] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[12:50:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
[12:50:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
[12:50:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:50:38] [Server thread/ERROR]: [FastCraftPlus] Unable to initialize RecipeUtil. Disabling.
[12:50:38] [Server thread/INFO]: [FastCraftPlus] Disabling FastCraftPlus v0.18

**Comment by BenWoodworth** [comment]
What server jar are you using? It looks like there's a missing file inside the server jar, and that's causing problems.

**Comment by RoboMWM** [comment]
Is this plugin compatible with

> 1.7.10-1614.46 (MC: 1.7.10)

**Comment by Xuwznln** [comment]
I am using the Thermos-1.7.10-1614-55

**Comment by Xuwznln** [comment]
I tested Thermos-1.7.10-1614-46.But the same error.

**Comment by BenWoodworth** [comment]
It looks like Thermos is missing classes that FastCraft+ relies on. I can see if there's anything I can do to work around it, but I don't think I'll be able to make FastCraft+ compatible with Thermos.

**Comment by BenWoodworth** [comment]
See if FastCraft+ v0.19 works for your server.

**Comment by Xuwznln** [comment]
I tested , and it worked.Many thanks!

**Comment by BenWoodworth** [comment]
No problem! Let me know if you find any more problems
