### ISSUE TITLE
Fastcraft GUI issue

### ISSUE THREAD

**Issue by AcesGamingUK** [BenWoodworth/FastCraftPlus#54]
# Description
right clicking on workbench
and issuing fastcraft commands

# Debug Output
<details><summary>Show **/fcadmin debug** output</summary>
```
========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.20.2
  git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
  1.8.8-R0.1-SNAPSHOT
  Java 1.8.0_91
Other Plugins (64):
  AirBar 2.1.1
  AntiCommandTab 3.8
  AnvilColors 1.3.1
  ArmorStandTools 2.1.2
  ASkyBlock 3.0.0.7
  AsyncWorldEdit 3.3.7
  AsyncWorldEditInjector 3.3.5
  AutoFarm 1.2.0
  AutomaticInventory 2.4
  AutoPickup 3.9
  Bank 2.3i
  Block-That-Command 1.2
  BlockRewards 1.0
  BottledExp 2.1.0.3
  BungeeFriendsGUI 2.0
  BuycraftX 10.0
  ChatColor 2.1
  CheckMyInventory 4.2.8.2
  ChopTree3 3.2.3
  ClearLag 2.9.0
  ColoredTablist 2.1.2
  CommandSign 1.4.0
  CustomItemsAPI 1.1.1
  CustomOreGen 1.0
  DabCore 1.0q
  EditableSign 2.1.0
  Essentials 2.0.1-b267
  EssentialsChat 2.0.1-b267
  EssentialsSpawn 2.0.1-b267
  FeatherBoard 3.10.1
  GAListener 1.4.4
  Greenhouses 5.4
  HakuApi 1.0.1
  HolographicDisplays 2.1.11
  KeepItems 1.3
  LightAPI 2.0.1
  Multiverse-Core 2.5-b699
  NaughtyMode 2.0.0
  NBTEditor 1.2
  NightVision 1.0
  NoCheatPlus 3.13.5-BETA-sMD5NET-b914
  OnlyProxyJoinAdvance 2.1
  PaintingSelector 1.0.1
  PermissionsEx 1.23.4
  PermissionTimer 2.0.1
  PluginManagerReloaded 1.0.0
  Prism 2.0.6-${env.BUILD_NUMBER}
  ProtocolLib 3.6.5-SNAPSHOT-b182
  RottenFlesh2Leather 1.0
  Shop 1.5.3.16
  SilkSpawners 3.7.1
  SimpleBroadcast 1.9.2
  SpigotBridge 1.0.0
  StaffProtect 1.2
  TitleManager 1.5.4
  TradeMe 3.4.0.7
  UnbreakingAnvils 1.0.2
  UsernameHistory 1.0
  Vault 1.5.6-b49
  VoidWorld 1.0
  VoteParty 1.4.1
  Votifier 1.9
  WorldEdit 6.1;no_git_id
  WorldGuard 6.1.2-SNAPSHOT;1651-93d454c
===========================================
```
</details>

# Stack Trace
<details><summary>Show stack trace</summary>
```
[Server thread/ERROR]: Could not pass event PlayerInteractEvent to FastCraftPlus v0.20.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
```
```
[16:58:03] [Server thread/INFO]: AcesGamingUK issued server command: /fc
[16:58:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'fastcraftplus:craft' in plugin FastCraftPlus v0.20.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:576) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.FormattedCommandAlias.execute(FormattedCommandAlias.java:38) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at co.kepler.fastcraftplus.recipes.FastRecipe.removeIngredients(FastRecipe.java:170) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.craftgui.layouts.LayoutRecipes.addRecipes(LayoutRecipes.java:38) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.craftgui.layouts.LayoutRecipesItems.updateRecipes(LayoutRecipesItems.java:31) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.craftgui.GUIFastCraft.updateLayout(GUIFastCraft.java:102) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.craftgui.GUIFastCraft.<init>(GUIFastCraft.java:54) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.commands.CmdCraft.open(CmdCraft.java:51) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.commands.CmdCraft.onCommand(CmdCraft.java:33) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.commands.CommandManager.onCommand(CommandManager.java:46) ~[FastCraftPlus.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 19 more
```
</details>

**Comment by RoboMWM** [comment]
Please include the full error.

**Comment by BenWoodworth** [comment]
Can you also provide the output of the "fca debug" command? I'm having trouble reproducing this.

**Comment by AcesGamingUK** [comment]
09.05 16:35:50 [Server] INFO [FastCraftPlus] FastCraft+ Debug Info:
09.05 16:35:50 [Server] INFO ========== FastCraft+ Debug Info ==========
09.05 16:35:50 [Server] INFO Versions:
09.05 16:35:50 [Server] INFO FastCraft+ v0.20.2
09.05 16:35:50 [Server] INFO git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
09.05 16:35:50 [Server] INFO 1.8.8-R0.1-SNAPSHOT
09.05 16:35:50 [Server] INFO Java 1.8.0_91
09.05 16:35:50 [Server] INFO Other Plugins (64):
09.05 16:35:50 [Server] INFO AirBar 2.1.1
09.05 16:35:50 [Server] INFO AntiCommandTab 3.8
09.05 16:35:50 [Server] INFO AnvilColors 1.3.1
09.05 16:35:50 [Server] INFO ArmorStandTools 2.1.2
09.05 16:35:50 [Server] INFO ASkyBlock 3.0.0.7
09.05 16:35:50 [Server] INFO AsyncWorldEdit 3.3.7
09.05 16:35:50 [Server] INFO AsyncWorldEditInjector 3.3.5
09.05 16:35:50 [Server] INFO AutoFarm 1.2.0
09.05 16:35:50 [Server] INFO AutomaticInventory 2.4
09.05 16:35:50 [Server] INFO AutoPickup 3.9
09.05 16:35:50 [Server] INFO Bank 2.3i
09.05 16:35:50 [Server] INFO Block-That-Command 1.2
09.05 16:35:50 [Server] INFO BlockRewards 1.0
09.05 16:35:50 [Server] INFO BottledExp 2.1.0.3
09.05 16:35:50 [Server] INFO BungeeFriendsGUI 2.0
09.05 16:35:50 [Server] INFO BuycraftX 10.0
09.05 16:35:50 [Server] INFO ChatColor 2.1
09.05 16:35:50 [Server] INFO CheckMyInventory 4.2.8.2
09.05 16:35:50 [Server] INFO ChopTree3 3.2.3
09.05 16:35:50 [Server] INFO ClearLag 2.9.0
09.05 16:35:50 [Server] INFO ColoredTablist 2.1.2
09.05 16:35:50 [Server] INFO CommandSign 1.4.0
09.05 16:35:50 [Server] INFO CustomItemsAPI 1.1.1
09.05 16:35:50 [Server] INFO CustomOreGen 1.0
09.05 16:35:50 [Server] INFO DabCore 1.0q
09.05 16:35:50 [Server] INFO EditableSign 2.1.0
09.05 16:35:50 [Server] INFO Essentials 2.0.1-b267
09.05 16:35:50 [Server] INFO EssentialsChat 2.0.1-b267
09.05 16:35:50 [Server] INFO EssentialsSpawn 2.0.1-b267
09.05 16:35:50 [Server] INFO FeatherBoard 3.10.1
09.05 16:35:50 [Server] INFO GAListener 1.4.4
09.05 16:35:50 [Server] INFO Greenhouses 5.4
09.05 16:35:50 [Server] INFO HakuApi 1.0.1
09.05 16:35:50 [Server] INFO HolographicDisplays 2.1.11
09.05 16:35:50 [Server] INFO KeepItems 1.3
09.05 16:35:50 [Server] INFO LightAPI 2.0.1
09.05 16:35:50 [Server] INFO Multiverse-Core 2.5-b699
09.05 16:35:50 [Server] INFO NaughtyMode 2.0.0
09.05 16:35:50 [Server] INFO NBTEditor 1.2
09.05 16:35:50 [Server] INFO NightVision 1.0
09.05 16:35:50 [Server] INFO NoCheatPlus 3.13.5-BETA-sMD5NET-b914
09.05 16:35:50 [Server] INFO OnlyProxyJoinAdvance 2.1
09.05 16:35:50 [Server] INFO PaintingSelector 1.0.1
09.05 16:35:50 [Server] INFO PermissionsEx 1.23.4
09.05 16:35:50 [Server] INFO PermissionTimer 2.0.1
09.05 16:35:50 [Server] INFO PluginManagerReloaded 1.0.0
09.05 16:35:50 [Server] INFO Prism 2.0.6-${env.BUILD_NUMBER}
09.05 16:35:50 [Server] INFO ProtocolLib 3.6.5-SNAPSHOT-b182
09.05 16:35:50 [Server] INFO RottenFlesh2Leather 1.0
09.05 16:35:50 [Server] INFO Shop 1.5.3.16
09.05 16:35:50 [Server] INFO SilkSpawners 3.7.1
09.05 16:35:50 [Server] INFO SimpleBroadcast 1.9.2
09.05 16:35:50 [Server] INFO SpigotBridge 1.0.0
09.05 16:35:50 [Server] INFO StaffProtect 1.2
09.05 16:35:50 [Server] INFO TitleManager 1.5.4
09.05 16:35:50 [Server] INFO TradeMe 3.4.0.7
09.05 16:35:50 [Server] INFO UnbreakingAnvils 1.0.2
09.05 16:35:50 [Server] INFO UsernameHistory 1.0
09.05 16:35:50 [Server] INFO Vault 1.5.6-b49
09.05 16:35:50 [Server] INFO VoidWorld 1.0
09.05 16:35:50 [Server] INFO VoteParty 1.4.1
09.05 16:35:50 [Server] INFO Votifier 1.9
09.05 16:35:50 [Server] INFO WorldEdit 6.1;no_git_id
09.05 16:35:50 [Server] INFO WorldGuard 6.1.2-SNAPSHOT;1651-93d454c
09.05 16:35:50 [Server] INFO ===========================================

**Comment by BenWoodworth** [comment]
Thanks. Is this also happening if you run a test server with only FastCraft+ on it?

**Comment by AcesGamingUK** [comment]
[16:44:20] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to FastCraftPlus v0.20.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException


and yeah getting same error

**Comment by AcesGamingUK** [comment]
i was using the one you sent me prior to this update

> https://github.com/BenWoodworth/FastCraftPlus/issues/41#issuecomment-213840147

**Comment by RoboMWM** [comment]
Please include the lines below `Caused by: java.lang.NullPointerException`

**Comment by AcesGamingUK** [comment]
there is nothing..... thats it

**Comment by RoboMWM** [comment]
Please paste the full log then in http://gist.github.com and link here then

**Comment by AcesGamingUK** [comment]
http://prntscr.com/b21mnu

**Comment by BenWoodworth** [comment]
Threads can make things tricky to debug. I'll take a look at this later and see if I can figure out what's happening.

**Comment by AcesGamingUK** [comment]
im sure its what was happening in my previus report before you sent me 

> https://github.com/BenWoodworth/FastCraftPlus/issues/41#issuecomment-213840147

**Comment by AcesGamingUK** [comment]
this it the error from 
/craft

[16:58:03] [Server thread/INFO]: AcesGamingUK issued server command: /fc
[16:58:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'fastcraftplus:craft' in plugin FastCraftPlus v0.20.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:576) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.FormattedCommandAlias.execute(FormattedCommandAlias.java:38) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at co.kepler.fastcraftplus.recipes.FastRecipe.removeIngredients(FastRecipe.java:170) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.craftgui.layouts.LayoutRecipes.addRecipes(LayoutRecipes.java:38) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.craftgui.layouts.LayoutRecipesItems.updateRecipes(LayoutRecipesItems.java:31) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.craftgui.GUIFastCraft.updateLayout(GUIFastCraft.java:102) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.craftgui.GUIFastCraft.<init>(GUIFastCraft.java:54) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.commands.CmdCraft.open(CmdCraft.java:51) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.commands.CmdCraft.onCommand(CmdCraft.java:33) ~[FastCraftPlus.jar:?]
        at co.kepler.fastcraftplus.commands.CommandManager.onCommand(CommandManager.java:46) ~[FastCraftPlus.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 19 more


thats it!

**Comment by BenWoodworth** [comment]
Can you see if this fixes the issue?

[FastCraftPlus.zip](https://github.com/BenWoodworth/FastCraftPlus/files/255392/FastCraftPlus.zip)

**Comment by AcesGamingUK** [comment]
yes working perfect thanks

**Comment by BenWoodworth** [comment]
Alright. Thanks for reporting the bug!
