### ISSUE TITLE
PlayerJoinEvent Failure

### ISSUE THREAD

**Issue by Ac3dUd3** [BenWoodworth/FastCraftPlus#77]
# Description
Error occuring on PlayerJoinEvent. i dont have any details for you, i didnt do anything for it to show, last thing i added to the server was this plugin https://www.spigotmc.org/resources/newitems.22783/

NullPointerException at:
co.kepler.fastcraftplus.recipes.Ingredient.removeIngredients([Ingredient.java:52](https://github.com/BenWoodworth/FastCraftPlus/blob/master/src/main/java/co/kepler/fastcraftplus/recipes/Ingredient.java#L52))

# Debug Output
<details><summary>Show **/fcadmin debug** output</summary>
```
========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.24.1
  git-Spigot-3ccadba-fb568fd (MC: 1.10)
  1.10-R0.1-SNAPSHOT
  Java 1.8.0_91
Other Plugins (68):
  AdminAnything 1.5
  ArmorStandTools 2.1.4
  ASkyBlock 3.0.1
  AsyncWorldEdit 2.2.2
  AsyncWorldEditInjector 2.2.2
  AuctionGUIPlus 1.0.15
  AutomaticInventory 2.5.5
  BackupsPlus 1.0.5
  Bank 2.4g
  BannerBoard 1.7.2
  BannerBoard_Shop 1.0.1
  ChatReaction 1.6.2
  ChatTagger 1.0.0
  ChestMaster 3.3
  ChestShop 4.0-r5
  Citizens 2.0.19-SNAPSHOT (build 1374)
  CleanroomGenerator 1.0.0
  ClearLag 2.9.1
  CrateReloaded 1.3.74
  DabCore 1.1a
  DailyRewards 1.2.3
  DeluxeChat 1.10.0
  DeluxeJoin 2.3.0
  DeluxeMenus 1.6.0
  DeluxeTags 1.7.1
  Emotes 1.6
  Essentials 2.0.1-b265
  EssentialsSpawn 2.0.1-b265
  eZProtector 3.6.8
  FeatherBoard 3.11.0
  Greenhouses 5.4
  HolographicDisplays 2.2
  IronElevators 1.1
  KitsPreview 1.0
  LiteBans 2.0.25
  LockupSalvage 1.0.0
  LockupStatus 1.0
  mcMMO 1.5.05-SNAPSHOT-b133
  MessageAnnouncer 1.6.2
  Multiverse-Core 2.5.0-SNAPSHOT-b722
  Multiverse-Portals 2.5.0-SNAPSHOT-b746
  MVdWPlaceholderAPI 1.0.0
  NewItems 1.0.9
  ParticleLIB 2.1.0
  PermissionsEx 1.23.4
  PlaceholderAPI 2.5.1
  PlugMan 2.1.1
  ProtocolLib 4.0.2-SNAPSHOT-b293
  PulseHealth 1.4.1
  React 2.3.3p
  SelectionVisualizer 1.4.2.0
  SignEditor 1.07
  Signs 1.9.7
  SilkSpawners 3.7.3
  Smileychat 3.2
  Spawntp 1.0.0
  StaffFacilities 2.5.5
  StaffList 3.5
  SuperbVote 0.3.1
  TintHealth 1.4.4
  TradeMe 3.4.2.2
  TryMe 4.6.5
  Vault 1.5.6-b49
  VoidSpawn 1.10.0
  Votifier 2.3.2.2
  WhatIsIt 1.3.9
  WorldEdit 6.1;no_git_id
  WorldGuard 6.1
===========================================
```
</details>

# Stack Trace
<details><summary>Show stack trace</summary>
```
[20:16:29 ERROR]: Could not pass event PlayerInteractEvent to FastCraftPlus v0.24.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:887) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at co.kepler.fastcraftplus.recipes.Ingredient.removeIngredients(Ingredient.java:52) ~[?:?]
        at co.kepler.fastcraftplus.recipes.FastRecipe.removeIngredients(FastRecipe.java:189) ~[?:?]
        at co.kepler.fastcraftplus.craftgui.buttons.GUIButtonRecipe.isVisible(GUIButtonRecipe.java:107) ~[?:?]
        at co.kepler.fastcraftplus.craftgui.layouts.LayoutRecipes.addRecipes(LayoutRecipes.java:40) ~[?:?]
        at co.kepler.fastcraftplus.craftgui.layouts.LayoutRecipesItems.updateRecipes(LayoutRecipesItems.java:31) ~[?:?]
        at co.kepler.fastcraftplus.craftgui.GUIFastCraft.updateLayout(GUIFastCraft.java:102) ~[?:?]
        at co.kepler.fastcraftplus.craftgui.GUIFastCraft.<init>(GUIFastCraft.java:54) ~[?:?]
        at co.kepler.fastcraftplus.craftgui.PlayerManager.onPlayerInteract(PlayerManager.java:47) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
        ... 17 more
```
</details>

**Comment by BenWoodworth** [comment]
Thanks for reporting this. I'll look into what might be causing it

**Comment by BenWoodworth** [comment]
v0.24.2 should fix this issue. Please let me know if you're still having problems.
