### ISSUE TITLE
Denizen and FastCraftPlus

### ISSUE THREAD

**Issue by Typhome** [BenWoodworth/FastCraftPlus#79]
I'm not sure if this is FastCraftPlus issue or Denizen... Both plugins are latest build.

``` 11.07 15:19:49 [Server] INFO ===========================================
11.07 15:19:49 [Server] INFO XrayInformer 3.3.7
11.07 15:19:49 [Server] INFO WorldGuard 6.1.2;e38d98d
11.07 15:19:49 [Server] INFO WorldEdit 6.1.3;7a097ca
11.07 15:19:49 [Server] INFO Votifier 1.9
11.07 15:19:49 [Server] INFO Vault 1.5.6-b49
11.07 15:19:49 [Server] INFO VanishNoPacket 3.20
11.07 15:19:49 [Server] INFO uSkyBlock 2.6.12
11.07 15:19:49 [Server] INFO TypPlugin 1.2
11.07 15:19:49 [Server] INFO StaffChat 1.3.1
11.07 15:19:49 [Server] INFO SkinsRestorer 12.4.1
11.07 15:19:49 [Server] INFO ProtocolLib 4.0.2-SNAPSHOT-b293
11.07 15:19:49 [Server] INFO PlugMan 2.1.
11.07 15:19:49 [Server] INFO PerWorldInventory 1.7.6
11.07 15:19:49 [Server] INFO PermissionsEx 1.23.4
11.07 15:19:49 [Server] INFO Multiverse-NetherPortals 2.5-b675
11.07 15:19:49 [Server] INFO Multiverse-Core 2.5-b717
11.07 15:19:49 [Server] INFO LWC 1.7.3
11.07 15:19:49 [Server] INFO Jobs 3.5.6
11.07 15:19:49 [Server] INFO HolographicDisplays 2.2
11.07 15:19:49 [Server] INFO GAListener 1.3.2
11.07 15:19:49 [Server] INFO EssentialsSpawn TeamCity
11.07 15:19:49 [Server] INFO EssentialsChat TeamCity
11.07 15:19:49 [Server] INFO Essentials TeamCity
11.07 15:19:49 [Server] INFO Dynmap-WorldGuard 0.90
11.07 15:19:49 [Server] INFO dynmap 2.3-1142
11.07 15:19:49 [Server] INFO Denizen 0.9.8-SNAPSHOT (build 1618)
11.07 15:19:49 [Server] INFO CraftBook 3.9-SNAPSHOT
11.07 15:19:49 [Server] INFO CoreProtect 2.12.0
11.07 15:19:49 [Server] INFO AuthMe 5.2-BETA3-b1134
11.07 15:19:49 [Server] INFO Other Plugins (29):
11.07 15:19:49 [Server] INFO Java 1.8.0_91
11.07 15:19:49 [Server] INFO 1.10.2-R0.1-SNAPSHOT
11.07 15:19:49 [Server] INFO git-Spigot-a9631d2-67b2424 (MC: 1.10.2)
11.07 15:19:49 [Server] INFO FastCraft+ v0.24.3
11.07 15:19:49 [Server] INFO Versions:
11.07 15:19:49 [Server] INFO ========== FastCraft+ Debug Info ========== ```

`[15:11:54] [Server thread/ERROR]: Could not pass event CraftItemEvent to Denizen v0.9.8-SNAPSHOT (build 1618)
org.bukkit.event.EventException
   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at co.kepler.fastcraftplus.util.RecipeUtil.callCraftItemEvent(RecipeUtil.java:229) [FastCraftPlus(2).jar:?]
   at co.kepler.fastcraftplus.recipes.FastRecipe.craft(FastRecipe.java:215) [FastCraftPlus(2).jar:?]
   at co.kepler.fastcraftplus.craftgui.buttons.GUIButtonRecipe.onClick(GUIButtonRecipe.java:115) [FastCraftPlus(2).jar:?]
   at co.kepler.fastcraftplus.api.gui.GUI$GUIListener.onInventoryClick(GUI.java:205) [FastCraftPlus(2).jar:?]
   at sun.reflect.GeneratedMethodAccessor868.invoke(Unknown Source) ~[?:?]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
   at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1854) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
   at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
   at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
   at net.aufdemrand.denizen.scripts.containers.core.ItemScriptHelper.processSpecialRecipes(ItemScriptHelper.java:328) ~[?:?]
   at net.aufdemrand.denizen.scripts.containers.core.ItemScriptHelper.specialRecipeClick(ItemScriptHelper.java:252) ~[?:?]
   at sun.reflect.GeneratedMethodAccessor775.invoke(Unknown Source) ~[?:?]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
   at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   ... 26 more`

**Comment by BenWoodworth** [comment]
Did you resolve the issue?

**Comment by Typhome** [comment]
Yes, Denizen plugin developer fixed it and released new build, tested with this build, after this it didn't throw error anymore, so it was Denizen issue. Thank you.

**Comment by BenWoodworth** [comment]
Okay, thanks for the update!
