### ISSUE TITLE
permission bug

### ISSUE THREAD

**Issue by 1434967947** [BenWoodworth/FastCraftPlus#80]
# Description
first, it don't work well with magic chest
second, i gave the fastcraft.use,fasccraft.command.craft ....... all permission to the default group but when i type "fc craft or fc toggle" it told me i don't have enough permission neither console do these command
# Debug Output
<details>
```
========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.24.3
  git-TacoSpigot-"d9d17b4" (MC: 1.10.2)
  1.10.2-R0.1-SNAPSHOT
  Java 1.8.0_91
Other Plugins (30):
  AncientGates 2.0.6
  AutoMessage 2.5.5
  ChestCommands 3.1.4
  ChopTree3 3.3.1
  ClearLag 2.9.1
  ColoredTags 2.1.3
  Essentials 2.0.1-b378
  EssentialsChat 2.0.1-b378
  EssentialsSpawn 2.0.1-b378
  GlobalMarket 2.0.0.20
  HolographicDisplays 2.2
  HolographicScoreboard 1.4.2
  KillerMoney 3.15
  LagMonitor 1.6
  LibsDisguises 9.0.8
  MagicChest 1.2.7r1
  mcMMO 1.5.06-SNAPSHOT-b145
  MultiKillW 3.1
  Multiverse-Core 2.5-b717
  PermissionsEx 1.23.4
  PlugMan 2.1.1
  ProtocolLib 4.0.2
  PvpTitles 2.5.5
  QuickShop 0.9.18
  Residence 4.4.1.0
  ScoreboardStats 0.9.8
  ScriptBlock 0.8.72CN
  Vault 1.5.6-b49
  WorldEdit 6.1.3;7a097ca
  WorldGuard 6.1.2;e38d98d
===========================================
```
</details>

# Stack Trace
<details>
```
ON stack traces
only magic chest throws exceptions


10:34:10 ERROR]: Error occurred while enabling MagicChest v1.2.7r1 (Is it up to date?)
java.lang.NoClassDefFoundError: co/kepler/fastcraftplus/FastCraft
	at org.zonedabone.magicchest.PluginCompatibility.getFastCraft(PluginCompatibility.java:49) ~[?:?]
	at org.zonedabone.magicchest.PluginCompatibility.printPluginCompatibilty(PluginCompatibility.java:88) ~[?:?]
	at org.zonedabone.magicchest.MagicChest.onEnable(MagicChest.java:21) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1391) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1196) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:796) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: co.kepler.fastcraftplus.FastCraft
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	... 25 more
```
</details>

**Comment by Jikoo** [comment]
Contact the author of MagicChest, they need to change the name of FastCraft in their softdepend to FastCraftPlus.

**Comment by BenWoodworth** [comment]
A few updates ago I renamed the main class from FastCraft to FastCraftPlus. References to the main class need to be renamed.
PluginCompatibility.java, lines 78-84:
```
    private static FastCraft getFastCraft() {
        Plugin plugin = Bukkit.getServer().getPluginManager().getPlugin("FastCraftPlus");
        if (plugin == null || !(plugin instanceof FastCraft)) {
            return null;
        }
        return (FastCraft)plugin;
    }
```

As for the permissions, I'm not positive what's happening. Can you try testing on a Spigot server (not TacoSpigot)  to see if that could be causing a problem?

**Comment by BenWoodworth** [comment]
This will hopefully be fixed soon. The developers are aware of the issue and its cause, and will be working to resolve it.
