### ISSUE TITLE
Strange console error.

### ISSUE THREAD

**Issue by MinecraftAdmin** [BenWoodworth/FastCraftPlus#87]
# Description
Seeing strange error in console

# Debug Output
<details><summary>Show **/fcadmin debug** output</summary>
<pre><code>[WARN] Unexpected exception while parsing console command "fcadmin debug"
[RAW] org.bukkit.command.CommandException: Unhandled exception executing command 'fcadmin' in plugin FastCraftPlus v0.24
[RAW] ?at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-850da7e-2e39de6]
[RAW] ?at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-850da7e-2e39de6]
[RAW] ?at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot.jar:git-Spigot-850da7e-2e39de6]
[RAW] ?at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:633) [spigot.jar:git-Spigot-850da7e-2e39de6]
[RAW] ?at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot.jar:git-Spigot-850da7e-2e39de6]
[RAW] ?at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot.jar:git-Spigot-850da7e-2e39de6]
[RAW] ?at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-850da7e-2e39de6]
[RAW] ?at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-850da7e-2e39de6]
[RAW] ?at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[RAW] Caused by: java.lang.NoClassDefFoundError: co/kepler/fastcraftplus/commands/CmdDebug$1
[RAW] ?at co.kepler.fastcraftplus.commands.CmdDebug.getSortedPlugins(CmdDebug.java:70) ~[?:?]
[RAW] ?at co.kepler.fastcraftplus.commands.CmdDebug.outputDebug(CmdDebug.java:51) ~[?:?]
[RAW] ?at co.kepler.fastcraftplus.commands.CmdDebug.onCommand(CmdDebug.java:26) ~[?:?]
[RAW] ?at co.kepler.fastcraftplus.commands.CmdFastCraftAdmin.onCommand(CmdFastCraftAdmin.java:27) ~[?:?]
[RAW] ?at co.kepler.fastcraftplus.commands.CommandManager.onCommand(CommandManager.java:46) ~[?:?]
[RAW] ?at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-850da7e-2e39de6]
[RAW] ?... 8 more
Cr8zy_ issued server command: /pv 6</code></pre>
</details>

# Stack Trace
<details><summary>Show stack trace</summary>
```
[06:29:10] [Server thread/ERROR]: Could not pass event PrepareItemCraftEvent to FastCraftPlus v0.24
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-850da7e-2e39de6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-850da7e-2e39de6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-850da7e-2e39de6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-850da7e-2e39de6]
	at haveric.recipeManager.Events$1.run(Events.java:418) [RecipeManager.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-850da7e-2e39de6]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-850da7e-2e39de6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot.jar:git-Spigot-850da7e-2e39de6]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-850da7e-2e39de6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-850da7e-2e39de6]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-850da7e-2e39de6]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at co.kepler.fastcraftplus.util.RecipeUtil.hashRecipe(RecipeUtil.java:239) ~[?:?]
	at co.kepler.fastcraftplus.util.RecipeUtil$ComparableRecipe.<init>(RecipeUtil.java:310) ~[?:?]
	at co.kepler.fastcraftplus.util.RecipeUtil.comparable(RecipeUtil.java:301) ~[?:?]
	at co.kepler.fastcraftplus.config.RecipesConfig.getRecipe(RecipesConfig.java:78) ~[?:?]
	at co.kepler.fastcraftplus.recipes.CraftingListener.onPrepareItemCraft(CraftingListener.java:21) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor873.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-850da7e-2e39de6]
	... 11 more
```
</details>

**Comment by BenWoodworth** [comment]
That's a weird error. Could you see if using the latest version resolves the issue? Can you also try running it on a server with no other plugins?

If you're still having problems, what version of Java are you using, and what is your server software (spigot, bukkit, etc. And what version)

Thanks for reporting the error.

**Comment by BenWoodworth** [comment]
Thanks for the issue report. Could you see if you still have this issue
with v0.25? I'll look into it more later when I get a chance.

**Comment by BenWoodworth** [comment]
I'm closing this because I can't reproduce it, and because of inactivity. I'll re-open it later if more information is provided.
